name: Node CI

on: [push, pull_request]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Test
      run: yarn test
      env:
        CI: true
    - name: Release
      uses: codfish/semantic-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: echo ${{ steps.semantic.outputs.release-version }}
    - run: echo "$OUTPUTS"
      env:
        OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
